export {
  TICKET_PRIORITIES,
  TICKET_SEVERITIES,
  TICKET_SOURCES,
  TICKET_STATUSES,
} from '@genius-support-os/contracts';

export type {
  JsonObject,
  RpcAddInternalTicketNotePayload,
  RpcAddInternalTicketNoteResponse,
  RpcAddTicketMessagePayload,
  RpcAddTicketMessageResponse,
  RpcAssignTicketPayload,
  RpcAssignTicketResponse,
  RpcCloseTicketPayload,
  RpcCloseTicketResponse,
  RpcCreateTicketPayload,
  RpcCreateTicketResponse,
  RpcReopenTicketPayload,
  RpcReopenTicketResponse,
  RpcUpdateTicketStatusPayload,
  RpcUpdateTicketStatusResponse,
  SupportAssignableAgent,
  SupportCustomer360,
  SupportCustomer360Contact,
  SupportCustomer360RecentEvent,
  SupportCustomer360RecentTicket,
  SupportTicketDetail,
  SupportTicketQueueItem,
  SupportTicketTimelineItem,
  TicketPriority,
  TicketSeverity,
  TicketSource,
  TicketStatus,
  TicketStatusUpdateTarget,
  Uuid,
} from '@genius-support-os/contracts';
